AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'
    - 'db/seeds/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/bundle'
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false